# Generated by Django 3.1.5 on 2021-05-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyersCounterOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_sign_date', models.DateField(help_text='Enter the Contract Sign Date', null=True)),
                ('contract_offer', models.CharField(choices=[('Purchase Agreement', 'Purchase Agreement'), ('Counter Offer', 'Counter Offer'), ('Other', 'Other')], help_text='Enter the contract offer for the counter offer', max_length=50, null=True)),
                ('counter_offer', models.IntegerField(help_text='Enter the buyers counter offer number', null=True)),
                ('other_contract_offer', models.CharField(help_text='Enter the other contract offer', max_length=100, null=True)),
                ('property_address', models.CharField(help_text='Enter the property address', max_length=100, null=True)),
                ('buyers_name', models.CharField(help_text="Enter the buyer's name", max_length=100, null=True)),
                ('sellers_name', models.CharField(help_text="Enter the seller's name", max_length=100, null=True)),
                ('envelope_id', models.CharField(help_text='Enter the Envelope ID', max_length=100, null=True)),
                ('envelope_id_1', models.CharField(help_text='Enter the Envelope ID', max_length=100, null=True)),
                ('sellers_id', models.IntegerField(help_text="Enter the seller's ID", null=True)),
                ('counter_offer_accept', models.BooleanField(help_text='Does the buyer want to accept the offer?', null=True)),
                ('other_terms_text_1', models.CharField(help_text='Enter the other terms', max_length=100, null=True)),
                ('other_terms_text_2', models.CharField(help_text='Enter the other terms', max_length=100, null=True)),
                ('other_terms_text_3', models.CharField(help_text='Enter the other terms', max_length=100, null=True)),
                ('other_terms_text_4', models.CharField(help_text='Enter the other terms', max_length=100, null=True)),
                ('other_terms', models.BooleanField(help_text='Does the buyer have any other terms?', null=True)),
                ('additional_terms', models.CharField(help_text='Enter the additional terms', max_length=100, null=True)),
                ('expiration_time', models.IntegerField(help_text='Enter the expiration time', null=True)),
                ('expiration_meridian', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Enter the expiration meridian', max_length=50, null=True)),
                ('expiration_date', models.DateField(help_text='Enter the expiration date', null=True)),
            ],
        ),
    ]
