# Generated by Django 3.1.5 on 2021-03-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SellersCounterOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_sign_date', models.DateField(help_text='Enter the Contract Sign Date', null=True)),
                ('multiple_offers', models.BooleanField(help_text='Does the seller have multiple offers?', null=True)),
                ('contract_offer', models.CharField(choices=[('Purchase Agreement', 'Purchase Agreement'), ('Counter Offer', 'Counter Offer'), ('Other', 'Other')], help_text='Enter the contract offer for the counter offer', max_length=50, null=True)),
                ('counter_offer', models.CharField(help_text='Enter the buyers counter offer number', max_length=100, null=True)),
                ('property_address', models.CharField(help_text='Enter the property address', max_length=100, null=True)),
                ('buyers_name', models.CharField(help_text="Enter the buyer's name", max_length=100, null=True)),
                ('sellers_name', models.CharField(help_text="Enter the seller's name", max_length=100, null=True)),
                ('offer_price_change', models.BooleanField(help_text='Does the seller want to change the offer price?', null=True)),
                ('new_offer_price', models.CharField(choices=[('Default', 'Default'), ('Highest And Best Price', 'Highest And Best Price')], help_text='Enter the new price', max_length=50, null=True)),
                ('escrow_company_change', models.BooleanField(help_text='Does the seller want to change the escrow company?', null=True)),
                ('escrow_company_name', models.CharField(help_text='Enter the escrow company name', max_length=100, null=True)),
                ('title_company_change', models.BooleanField(help_text='Does the seller want to change the title company?', null=True)),
                ('title_company_name', models.CharField(help_text='Enter the title company name', max_length=100, null=True)),
                ('termite_company_change', models.BooleanField(help_text='Does the seller want to change the termite company?', null=True)),
                ('termite_company_name', models.CharField(help_text='Enter the termite company name', max_length=100, null=True)),
                ('other_terms', models.BooleanField(help_text='Does the seller have any other terms?', null=True)),
                ('other_terms_text', models.CharField(help_text='Enter the additional terms', max_length=100, null=True)),
                ('remove_appraisal_contingence', models.BooleanField(help_text='Does the seller want to remove appraisal contingence?', null=True)),
                ('remove_inspection_contingence', models.BooleanField(help_text='Does the seller want to remove inspection contingence?', null=True)),
                ('loan_qualification_proofs', models.BooleanField(help_text='Does the seller want buyer to provide loan qualification prrofs?', null=True)),
                ('addenda', models.BooleanField(help_text='Does the seller have any addenda?', null=True)),
                ('addenda_name_1', models.BooleanField(help_text="Does the seller have any addenda's number?", null=True)),
                ('addenda_name_2', models.CharField(help_text='Enter the addenda text', max_length=100, null=True)),
                ('addenda_name_3', models.CharField(help_text='Enter the addenda text', max_length=100, null=True)),
                ('expiration_time', models.IntegerField(help_text='Enter the expiration time', null=True)),
                ('expiration_meridian', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], help_text='Enter the expiration meridian', max_length=50, null=True)),
                ('expiration_date', models.DateField(help_text='Enter the expiration date', null=True)),
                ('envelope_id', models.CharField(help_text='Enter the Envelope ID', max_length=100, null=True)),
                ('buyers_id', models.IntegerField(help_text="Enter the buyer's ID", null=True)),
            ],
        ),
    ]
