# Generated by Django 3.1.5 on 2021-01-24 03:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymenttype', models.CharField(choices=[('c', 'Cash'), ('l', 'Loan')], help_text='Enter a type of payment', max_length=50)),
                ('downpayment', models.IntegerField(help_text='Enter the amount of down payment for the loan')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(help_text='Enter the property apartment', max_length=50)),
                ('street', models.CharField(help_text='Enter the property street', max_length=50)),
                ('city', models.CharField(help_text='Enter a type of property city', max_length=50)),
                ('state', models.CharField(help_text='Enter a type of property state', max_length=50)),
                ('country', models.CharField(help_text='Enter a type of property country', max_length=50)),
                ('pincode', models.IntegerField(help_text='Enter a type of property pincode')),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular buyer', primary_key=True, serialize=False)),
                ('firstname', models.CharField(help_text='Enter the first name', max_length=100)),
                ('secondname', models.CharField(help_text='Enter the last name', max_length=100)),
                ('email', models.EmailField(help_text='Enter the email address', max_length=254)),
                ('phone', models.IntegerField(help_text='Enter the phone number')),
                ('offerprice', models.IntegerField(help_text='Enter the offer price')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='buyers_offer.payment')),
                ('propertyaddress', models.ManyToManyField(help_text='Enter the address of property', to='buyers_offer.PropertyAddress')),
            ],
            options={
                'ordering': ['firstname', 'secondname'],
            },
        ),
    ]
