# Generated by Django 3.1.5 on 2021-02-08 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the first name', max_length=100)),
                ('last_name', models.CharField(help_text='Enter the last name', max_length=100)),
                ('email', models.EmailField(help_text='Enter the email address', max_length=254)),
                ('phone', models.IntegerField(help_text='Enter the phone number')),
                ('offer_price', models.IntegerField(help_text='Enter the offer price')),
                ('escrow_date', models.DateField(help_text='Enter the Escrow Dose Date', null=True)),
                ('escrow_days', models.IntegerField(help_text='Enter the Escrow Dose Days', null=True)),
                ('ad', models.BooleanField(help_text='Enter the acknowledgement of form AD', null=True)),
                ('agent', models.BooleanField(help_text='Does the buyer have an agent?', null=True)),
                ('dual_brokerage', models.BooleanField(help_text='Is the brokerage dual?', null=True)),
                ('prbs', models.BooleanField(help_text='Enter the acknowledgement of form PRBS', null=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='BuyerAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage_firm', models.CharField(help_text="Enter the buyer's brokerage firm", max_length=100, null=True)),
                ('brokerage_license_number', models.CharField(help_text="Enter the buyer's brokerage license number", max_length=100, null=True)),
                ('agent_name', models.CharField(help_text="Enter the buyer's agent name", max_length=100, null=True)),
                ('agent_license_number', models.CharField(help_text="Enter the buyer's agent license number", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Loan', 'Loan')], help_text='Enter a type of payment', max_length=50)),
                ('down_payment', models.IntegerField(help_text='Enter the amount of down payment for the loan')),
            ],
        ),
        migrations.CreateModel(
            name='SellerAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brokerage_firm', models.CharField(help_text="Enter the seller's brokerage firm", max_length=100, null=True)),
                ('brokerage_license_number', models.CharField(help_text="Enter the seller's brokerage license number", max_length=100, null=True)),
                ('agent_name', models.CharField(help_text="Enter the seller's agent name", max_length=100, null=True)),
                ('agent_license_number', models.CharField(help_text="Enter the seller's agent license number", max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.BooleanField(help_text='Does the seller have an agent?', null=True)),
                ('agent_firm', models.ManyToManyField(help_text="Enter the seller's agent", to='buyers_offer.SellerAgent')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(help_text='Enter the property apartment', max_length=50)),
                ('street', models.CharField(help_text='Enter the property street', max_length=50)),
                ('city', models.CharField(help_text='Enter the property city', max_length=50)),
                ('county', models.CharField(help_text='Enter the property county', max_length=50)),
                ('zipcode', models.IntegerField(help_text='Enter the property zipcode')),
                ('parcel_number', models.CharField(help_text='Enter the parcel number', max_length=50)),
                ('buyer', models.ManyToManyField(help_text='Enter the buyer information', to='buyers_offer.Buyer')),
                ('seller', models.ManyToManyField(help_text='Enter the seller information', to='buyers_offer.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='agent_firm',
            field=models.ManyToManyField(help_text="Enter the buyer's agent", to='buyers_offer.BuyerAgent'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='payment',
            field=models.ManyToManyField(help_text='Enter the payment', to='buyers_offer.Payment'),
        ),
    ]
