# Generated by Django 3.1.5 on 2021-02-06 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='down_payment',
            field=models.IntegerField(default=1, help_text='Enter the amount of down payment for the loan'),
            preserve_default=False,
        ),
    ]
