# Generated by Django 3.1.5 on 2021-02-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='primary_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
