# Generated by Django 3.1.5 on 2021-03-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersoffer',
            name='envelope_id',
            field=models.CharField(help_text='Enter the envelope ID', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='spouse_email',
            field=models.EmailField(default=1, help_text='Enter the spouse email address', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='spouse_first_name',
            field=models.CharField(default=1, help_text='Enter the spouse first name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='spouse_last_name',
            field=models.CharField(default=1, help_text='Enter the spouse last name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='primary_key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
