# Generated by Django 3.1.5 on 2021-02-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersoffer',
            name='additional_terms',
            field=models.CharField(help_text='Enter the additional financing terms', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='deposit_due',
            field=models.CharField(choices=[('Business days after acceptance', 'Business days after acceptance'), ('Other', 'Other')], help_text='Enter the type of deposit due', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='deposit_payment_type',
            field=models.CharField(choices=[("Cashier's Check", "Cashier's Check"), ('Personal Check', 'Personal Check'), ('Other', 'Other')], help_text='Enter the type of deposit payment', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='first_loan_adjustable_loan_rate',
            field=models.IntegerField(help_text='Enter the adjustable loan rate', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='first_loan_amount',
            field=models.IntegerField(help_text='Enter the first loan amount', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='first_loan_fixed_rate',
            field=models.IntegerField(help_text='Enter the fixed loan rate', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='first_loan_max_points',
            field=models.IntegerField(help_text='Enter the maximum points to pay', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='first_loan_type',
            field=models.CharField(choices=[('Conventional Loan', 'Conventional Loan'), ('FHA', 'FHA'), ('VA', 'VA'), ('Seller Financing', 'Seller Financing'), ('AFA', 'AFA'), ('Other', 'Other')], default='Conventional Loan', help_text='Enter the type of first loan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='first_loan_type_other',
            field=models.CharField(help_text='Enter additional details for loan type', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='fund_verification',
            field=models.CharField(choices=[('Conventional Loan', 'Conventional Loan'), ('FHA', 'FHA'), ('VA', 'VA'), ('Seller Financing', 'Seller Financing'), ('AFA', 'AFA'), ('Other', 'Other')], help_text='Enter the days needed for fund verification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='fund_verification_other',
            field=models.CharField(help_text='Enter additional details for fund verification', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='initial_deposit',
            field=models.IntegerField(help_text='Enter the initial deposit', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='other_deposit_due',
            field=models.CharField(help_text='Enter the other deposit due', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='other_deposit_payment_type',
            field=models.CharField(help_text='Enter the other deposit payment type', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='second_loan',
            field=models.BooleanField(help_text='Does the buyer have a second loan', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='second_loan_adjustable_loan_rate',
            field=models.IntegerField(help_text='Enter the adjustable loan rate', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='second_loan_amount',
            field=models.IntegerField(help_text='Enter the first loan amount', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='second_loan_fixed_rate',
            field=models.IntegerField(help_text='Enter the fixed loan rate', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='second_loan_max_points',
            field=models.IntegerField(help_text='Enter the maximum points to pay', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='second_loan_type',
            field=models.CharField(choices=[('Conventional Loan', 'Conventional Loan'), ('FHA', 'FHA'), ('VA', 'VA'), ('Seller Financing', 'Seller Financing'), ('AFA', 'AFA'), ('Other', 'Other')], default='Conventional Loan', help_text='Enter the type of first loan', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='second_loan_type_other',
            field=models.CharField(help_text='Enter additional details for loan type', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='buyersoffer',
            name='down_payment',
            field=models.IntegerField(help_text='Enter the amount of down payment for the loan', null=True),
        ),
    ]
