# Generated by Django 3.1.5 on 2021-02-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0002_auto_20210214_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyersoffer',
            old_name='other_deposit_due',
            new_name='deposit_due_other',
        ),
        migrations.RenameField(
            model_name='buyersoffer',
            old_name='other_deposit_payment_type',
            new_name='deposit_payment_type_other',
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='down_payment_days',
            field=models.IntegerField(help_text='Enter the amount of down payment days for the loan', null=True),
        ),
    ]
