# Generated by Django 3.1.5 on 2021-03-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0002_auto_20210223_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersoffer',
            name='spouse_email',
            field=models.EmailField(default=1, help_text='Enter the spouse email address', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='spouse_first_name',
            field=models.CharField(default=1, help_text='Enter the spouse first name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='spouse_last_name',
            field=models.CharField(default=1, help_text='Enter the spouse last name', max_length=100),
            preserve_default=False,
        ),
    ]
