# Generated by Django 3.1.5 on 2021-03-07 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0003_auto_20210306_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersoffer',
            name='envelope_id',
            field=models.CharField(help_text='Enter the envelope ID', max_length=100, null=True),
        ),
    ]
