# Generated by Django 3.1.5 on 2021-02-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0003_auto_20210214_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersoffer',
            name='agreement_contingency',
            field=models.BooleanField(help_text='Is this agreement contingent upon sale of any property owned by the buyer?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='appraisal_contingency',
            field=models.BooleanField(help_text='Does the buyer have an appraisal contingency?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='appraisal_contingency_days',
            field=models.IntegerField(help_text='Enter the appraisal contingency removal days', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='loan_contingency',
            field=models.BooleanField(help_text='Does the buyer have a loan contingency?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='loan_contingency_days',
            field=models.IntegerField(help_text='Enter the loan contingency removal days', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='loan_prequalification_days',
            field=models.IntegerField(help_text='Enter the loan prequalification days', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='other_terms',
            field=models.CharField(help_text='Enter the other terms', max_length=100, null=True),
        ),
    ]
