# Generated by Django 3.1.5 on 2021-02-15 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0004_auto_20210214_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyersoffer',
            name='fund_verification',
            field=models.CharField(choices=[('Attached with this agreement', 'Attached with this agreement'), ('3 or more days', '3 or more days')], help_text='Enter the days needed for fund verification', max_length=50, null=True),
        ),
    ]
