# Generated by Django 3.1.5 on 2021-01-24 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0004_auto_20210123_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.IntegerField(help_text='Unique ID for this payment', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='id',
            field=models.IntegerField(help_text='Unique ID for this property', primary_key=True, serialize=False),
        ),
    ]
