# Generated by Django 3.1.5 on 2021-02-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0005_auto_20210214_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersoffer',
            name='city_transfer',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Seller', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='county_transfer',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Seller', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='environmental_report',
            field=models.BooleanField(help_text='Is there an environmental report?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='escrow_fee',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller'), ('Both', 'Both')], help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='escrow_general_provision',
            field=models.IntegerField(help_text="Enter the escrow holder's general provision", null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='escrow_holder',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Seller', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='government_inspection',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='government_retrofit',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='hoa_document',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Seller', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='hoa_transfer',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Seller', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='insurance_claim_report',
            field=models.BooleanField(help_text='Is there an insurance claim report?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='natural_hazard',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='private_transfer',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Seller', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='section_1_termite',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Seller', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='smoke_alarm',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='tax_report',
            field=models.BooleanField(help_text='Is there a tax report?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='tc_fee',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Buyer', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='termite_inspection_report',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='title_insurance',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Seller', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='title_policy',
            field=models.CharField(help_text="Enter the institute for preparing the owner's title policy", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='upgraded_warranty',
            field=models.BooleanField(help_text='Is it an upgraded warranty?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='warranty_air_conditioner',
            field=models.BooleanField(help_text='Would the warranty cover air conditioner?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='warranty_buyers_choice',
            field=models.BooleanField(help_text="Shall the warranty be up to buyer's choice?", null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='warranty_company',
            field=models.CharField(help_text='Enter the warranty company', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='warranty_maximal_cost',
            field=models.IntegerField(help_text='Enter the maximal cost for warranty', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='warranty_plan',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], default='Seller', help_text='Enter the type of cost allocation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='warranty_pool_spa',
            field=models.BooleanField(help_text='Would the warranty cover pool/spa?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='warranty_waive',
            field=models.BooleanField(help_text='Would the buyer waive the warranty?', null=True),
        ),
    ]
