# Generated by Django 3.1.5 on 2021-01-24 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0006_auto_20210123_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='payment',
        ),
        migrations.AddField(
            model_name='buyer',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='buyers_offer.payment'),
        ),
    ]
