# Generated by Django 3.1.5 on 2021-02-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0006_auto_20210215_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyersoffer',
            name='additional_items',
            field=models.CharField(help_text='Enter the additional items', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='buyer_possession_1',
            field=models.CharField(help_text='Enter the time of close of escrow', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='buyer_possession_2',
            field=models.CharField(help_text='Enter the time of close of escrow', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='buyer_possession_3',
            field=models.CharField(help_text='Enter the time of close of escrow', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='buyer_primary_residence',
            field=models.BooleanField(default=True, help_text="Is the property the buyer's primary residence?", null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='cancel_agreement',
            field=models.IntegerField(help_text='Enter the days each party shall give the other party while cancelling this agreement', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='condominium',
            field=models.IntegerField(help_text='Enter the disclosure to buyer if the property is condominium', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='days_perform',
            field=models.IntegerField(help_text='Enter the days to perform', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='deliver_report',
            field=models.IntegerField(help_text='Enter the days after acceptance that seller has to deliver all the reports', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='dryers_washers',
            field=models.BooleanField(help_text='Would the sale include all the dryers and washers?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='exceptions_1',
            field=models.CharField(help_text='Enter the exceptions', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='exceptions_2',
            field=models.CharField(help_text='Enter the exceptions', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='exceptions_3',
            field=models.CharField(help_text='Enter the exceptions', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='expiration_date',
            field=models.DateField(help_text='Enter the expiration date', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='expiration_time',
            field=models.CharField(help_text='Enter the expiration time', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='final_verification',
            field=models.IntegerField(help_text='When to make final verification of condition', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='inspection_contingency',
            field=models.BooleanField(help_text="Enter the buyer's claim inspection contingency", null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='not_owned_seller',
            field=models.CharField(help_text='Enter the items not owned by seller', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='phone_automation_system',
            field=models.BooleanField(default=True, help_text='Would the sale include all the refrigerators?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='property_access',
            field=models.IntegerField(help_text='Enter the days after acceptance that buyer shall have access to the property', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='property_vacant_1',
            field=models.IntegerField(help_text='Enter the number of days prior to close of escrow to vacant the property', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='property_vacant_2',
            field=models.BooleanField(help_text='Enter the number of days prior to close of escrow to vacant the property', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='refrigerators',
            field=models.BooleanField(help_text='Would the sale include all the refrigerators?', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='remove_inspection_contingency',
            field=models.IntegerField(help_text='Enter the days after acceptance that seller has to deliver all the reports', null=True),
        ),
        migrations.AddField(
            model_name='buyersoffer',
            name='stove',
            field=models.BooleanField(help_text='Would the sale include all the stoves?', null=True),
        ),
    ]
