# Generated by Django 3.1.5 on 2021-01-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0008_auto_20210123_2048'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyer',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='offerprice',
            new_name='offer_price',
        ),
        migrations.RenameField(
            model_name='buyer',
            old_name='propertyaddress',
            new_name='property_address',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='downpayment',
            new_name='down_payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='paymenttype',
            new_name='payment_type',
        ),
    ]
