# Generated by Django 3.1.5 on 2021-02-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0009_auto_20210123_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='propertyaddress',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='propertyaddress',
            name='state',
        ),
        migrations.AddField(
            model_name='propertyaddress',
            name='county',
            field=models.CharField(default=None, help_text='Enter a type of property county', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyaddress',
            name='zipcode',
            field=models.IntegerField(default=None, help_text='Enter a type of property zipcode'),
            preserve_default=False,
        ),
    ]
