# Generated by Django 3.1.5 on 2021-02-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0010_auto_20210131_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyaddress',
            name='parcel_number',
            field=models.CharField(help_text='Enter the parcel number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='city',
            field=models.CharField(help_text='Enter the property city', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='county',
            field=models.CharField(help_text='Enter the property county', max_length=50),
        ),
        migrations.AlterField(
            model_name='propertyaddress',
            name='zipcode',
            field=models.IntegerField(help_text='Enter the property zipcode'),
        ),
    ]
