# Generated by Django 3.1.5 on 2021-02-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0011_auto_20210201_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyaddress',
            name='parcel_number',
            field=models.CharField(default=1, help_text='Enter the parcel number', max_length=50),
            preserve_default=False,
        ),
    ]
