# Generated by Django 3.1.5 on 2021-02-02 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buyers_offer', '0012_auto_20210201_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='escrow_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Enter the Escrow Dose Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buyer',
            name='escrow_days',
            field=models.IntegerField(default=5, help_text='Enter the Escrow Dose Days'),
            preserve_default=False,
        ),
    ]
